# Copied from ur_description/config/ur5e/joint_limits.yaml
joint_limits:
  shoulder_pan_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 360.0 # degrees
    max_velocity: 180.0 # degrees/s
    min_position: -360.0 # degrees
  shoulder_lift_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 360.0
    max_velocity: 180.0
    min_position: -360.0
  elbow_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    max_position: 180.0
    max_velocity: 180.0
    min_position: -180.0
  wrist_1_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 360.0
    max_velocity: 180.0
    min_position: -360.0
  wrist_2_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 360.0
    max_velocity: 180.0
    min_position: -360.0
  wrist_3_joint:
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 28.0
    max_position: 360.0
    max_velocity: 180.0
    min_position: -360.0

